### PR TITLE
add get_configlets function

### PR DESCRIPTION
**Pull request by brokenpackets**

### CODE REVIEW

**Comment by brokenpackets** [comment]
Added function for get_configlets to cvp_api.py

default pulls all configlets, can be filtered down to specific types of configlets, or search strings.

**Comment by mharista** [comment]
Can you add tests associated with this new function?

**Comment by brokenpackets** [comment]
Added test matching some of the other get_{items}. Let me know if you think we need something more specific.

**Comment by brokenpackets** [comment]
Closing out - will review current dev branch later and submit fresh PR if still required.

**Pull request closed without merging**
